---
  - name: restart Kibana
    service:
      name: kibana
      state: restarted
    when: ansible_virtualization_type != 'docker'
  - name: start Kibana
    command:
      cmd:  su -l kibana -s /bin/bash -c "/usr/share/kibana/bin/kibana &"
      #cmd: "/usr/share/kibana/bin/kibana --allow-root &"
      #cmd: "ps aux"
      creates: /tmp/.kibana.lock
    when: ansible_virtualization_type == 'docker'
