---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: elastic-instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
  - name: kibana-instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - create
    - syntax
    - converge
    - idempotence
    - verify
    - destroy